# Generated by Django 5.2.10 on 2026-02-23 08:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("catalog", "0003_category_normalized_name_tag_normalized_name"),
        ("catalog", "0004_alter_category_id_alter_category_weight_and_more"),
    ]

    dependencies = [
        ("catalog", "0001_squashed_0002_alter_item_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="normalized_name",
            field=models.CharField(
                default=" ",
                editable=False,
                help_text="нормализованное имя с проверкой на уникальность",
                max_length=150,
                unique=True,
                verbose_name="нормализованное имя",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tag",
            name="normalized_name",
            field=models.CharField(
                default="",
                editable=False,
                help_text="нормализованное имя с проверкой на уникальность",
                max_length=150,
                unique=True,
                verbose_name="нормализованное имя",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="category",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="weight",
            field=models.PositiveIntegerField(
                default=100,
                help_text="число из диапазона [1;32767]",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(32767),
                ],
                verbose_name="вес",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.ForeignKey(
                help_text="выберите категорию",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="related",
                to="catalog.category",
                verbose_name="категория",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="tags",
            field=models.ManyToManyField(
                help_text="выберите теги для товара",
                related_name="related",
                to="catalog.tag",
                verbose_name="тег",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterModelTable(
            name="category",
            table=None,
        ),
        migrations.AlterModelTable(
            name="item",
            table=None,
        ),
        migrations.AlterModelTable(
            name="tag",
            table=None,
        ),
    ]
