# Generated by Django 5.2.10 on 2026-02-24 14:33

import django.db.models.deletion
from django.db import migrations, models

import catalog.validators


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_itemimage_itemmainimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                help_text=(
                    "до 200 символов, уникальное значение, "
                    "только цифры, латиница и символы - и _"
                ),
                max_length=200,
                unique=True,
                verbose_name="слаг",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.ForeignKey(
                help_text="выберите категорию",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="catalog.category",
                verbose_name="категория",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="text",
            field=models.TextField(
                help_text=(
                    "текст из 2+ слов, в котором содержится "
                    "превосходно/роскошно"
                ),
                validators=[
                    catalog.validators.ValidateMustContain(
                        "превосходно", "роскошно"
                    )
                ],
                verbose_name="текст",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.SlugField(
                help_text=(
                    "до 200 символов, уникальное значение, "
                    "только цифры, латиница и символы - и _"
                ),
                max_length=200,
                unique=True,
                verbose_name="слаг",
            ),
        ),
    ]
