# Generated by Django 5.2.10 on 2026-03-25 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "catalog",
            "0008_item_is_on_main_alter_item_category_alter_item_tags",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="normalized_name",
            field=models.CharField(
                editable=False,
                help_text="нормализованное имя",
                max_length=150,
                verbose_name="нормализованное имя",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="normalized_name",
            field=models.CharField(
                editable=False,
                help_text="нормализованное имя",
                max_length=150,
                verbose_name="нормализованное имя",
            ),
        ),
    ]
