name: CI

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pip install black flake8
      - run: black --check --config ./pyproject.toml .
      - run: flake8 --config .flake8 --verbose .

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pip install -r requirements/test.txt
      - run: |
          cd lyceum
          python manage.py test
